<?php
$countries = [
    ["name" => "Andorra", "name_no_accents" => "Andorra"],
    ["name" => "Emirados Árabes Unidos", "name_no_accents" => "Emirados Arabes Unidos"],
    ["name" => "Afeganistão", "name_no_accents" => "Afeganistao"],
    ["name" => "Anguila", "name_no_accents" => "Anguila"],
    ["name" => "Albânia", "name_no_accents" => "Albania"],
    ["name" => "Armênia", "name_no_accents" => "Armenia"],
    ["name" => "Angola", "name_no_accents" => "Angola"],
    ["name" => "Antártida", "name_no_accents" => "Antartida"],
    ["name" => "Argentina", "name_no_accents" => "Argentina"],
    ["name" => "Áustria", "name_no_accents" => "Austria"],
    ["name" => "Austrália", "name_no_accents" => "Australia"],
    ["name" => "Azerbaijão", "name_no_accents" => "Azerbaijao"],
    ["name" => "Bósnia e Herzegovina", "name_no_accents" => "Bosnia e Herzegovina"],
    ["name" => "Barbados", "name_no_accents" => "Barbados"],
    ["name" => "Bangladesh", "name_no_accents" => "Bangladesh"],
    ["name" => "Bélgica", "name_no_accents" => "Belgica"],
    ["name" => "Burquina Fasso", "name_no_accents" => "Burquina Fasso"],
    ["name" => "Bulgária", "name_no_accents" => "Bulgaria"],
    ["name" => "Bahrein", "name_no_accents" => "Bahrein"],
    ["name" => "Burundi", "name_no_accents" => "Burundi"],
    ["name" => "Benim", "name_no_accents" => "Benim"],
    ["name" => "Bermudas", "name_no_accents" => "Bermudas"],
    ["name" => "Brunei", "name_no_accents" => "Brunei"],
    ["name" => "Bolívia", "name_no_accents" => "Bolivia"],
    ["name" => "Brasil", "name_no_accents" => "Brasil"],
    ["name" => "Bahamas", "name_no_accents" => "Bahamas"],
    ["name" => "Butão", "name_no_accents" => "Butao"],
    ["name" => "Botswana", "name_no_accents" => "Botswana"],
    ["name" => "Bielorrússia", "name_no_accents" => "Bielorrussia"],
    ["name" => "Belize", "name_no_accents" => "Belize"],
    ["name" => "Canadá", "name_no_accents" => "Canada"],
    ["name" => "República Democrática do Congo", "name_no_accents" => "Republica Democratica do Congo"],
    ["name" => "República Centro-Africana", "name_no_accents" => "Republica Centro-Africana"],
    ["name" => "República do Congo", "name_no_accents" => "Republica do Congo"],
    ["name" => "Suíça", "name_no_accents" => "Suica"],
    ["name" => "Costa do Marfim", "name_no_accents" => "Costa do Marfim"],
    ["name" => "Chile", "name_no_accents" => "Chile"],
    ["name" => "Camarões", "name_no_accents" => "Camaroes"],
    ["name" => "China", "name_no_accents" => "China"],
    ["name" => "Colômbia", "name_no_accents" => "Colombia"],
    ["name" => "Costa Rica", "name_no_accents" => "Costa Rica"],
    ["name" => "Cuba", "name_no_accents" => "Cuba"],
    ["name" => "Cabo Verde", "name_no_accents" => "Cabo Verde"],
    ["name" => "Chipre", "name_no_accents" => "Chipre"],
    ["name" => "República Tcheca", "name_no_accents" => "Republica Tcheca"],
    ["name" => "Alemanha", "name_no_accents" => "Alemanha"],
    ["name" => "Djibouti", "name_no_accents" => "Djibouti"],
    ["name" => "Dinamarca", "name_no_accents" => "Dinamarca"],
    ["name" => "Dominica", "name_no_accents" => "Dominica"],
    ["name" => "República Dominicana", "name_no_accents" => "Republica Dominicana"],
    ["name" => "Argélia", "name_no_accents" => "Argelia"],
    ["name" => "Equador", "name_no_accents" => "Equador"],
    ["name" => "Estônia", "name_no_accents" => "Estonia"],
    ["name" => "Egito", "name_no_accents" => "Egito"],
    ["name" => "Eritreia", "name_no_accents" => "Eritreia"],
    ["name" => "Espanha", "name_no_accents" => "Espanha"],
    ["name" => "Etiópia", "name_no_accents" => "Etiopia"],
    ["name" => "Finlândia", "name_no_accents" => "Finlandia"],
    ["name" => "França", "name_no_accents" => "Franca"],
    ["name" => "Gabão", "name_no_accents" => "Gabao"],
    ["name" => "Reino Unido", "name_no_accents" => "Reino Unido"],
    ["name" => "Inglaterra", "name_no_accents" => "Inglaterra"],
    ["name" => "Irlanda do Norte", "name_no_accents" => "Irlanda do Norte"],
    ["name" => "Escócia", "name_no_accents" => "Escocia"],
    ["name" => "País de Gales", "name_no_accents" => "Pais de Gales"],
    ["name" => "Granada", "name_no_accents" => "Granada"],
    ["name" => "Geórgia", "name_no_accents" => "Georgia"],
    ["name" => "Guiana Francesa", "name_no_accents" => "Guiana Francesa"],
    ["name" => "Gana", "name_no_accents" => "Gana"],
    ["name" => "Gibraltar", "name_no_accents" => "Gibraltar"],
    ["name" => "Groelândia", "name_no_accents" => "Groelandia"],
    ["name" => "Gâmbia", "name_no_accents" => "Gambia"],
    ["name" => "Guiné", "name_no_accents" => "Guine"],
    ["name" => "Guadalupe", "name_no_accents" => "Guadalupe"],
    ["name" => "Guiné Equatorial", "name_no_accents" => "Guine Equatorial"],
    ["name" => "Grécia", "name_no_accents" => "Grecia"],
    ["name" => "Guatemala", "name_no_accents" => "Guatemala"],
    ["name" => "Guiné-Bissau", "name_no_accents" => "Guine-Bissau"],
    ["name" => "Guiana", "name_no_accents" => "Guiana"],
    ["name" => "Hong Kong", "name_no_accents" => "Hong Kong"],
    ["name" => "Honduras", "name_no_accents" => "Honduras"],
    ["name" => "Croácia", "name_no_accents" => "Croacia"],
    ["name" => "Haiti", "name_no_accents" => "Haiti"],
    ["name" => "Hungria", "name_no_accents" => "Hungria"],
    ["name" => "Indonésia", "name_no_accents" => "Indonesia"],
    ["name" => "Irlanda", "name_no_accents" => "Irlanda"],
    ["name" => "Israel", "name_no_accents" => "Israel"],
    ["name" => "Índia", "name_no_accents" => "India"],
    ["name" => "Iraque", "name_no_accents" => "Iraque"],
    ["name" => "Irã", "name_no_accents" => "Ira"],
    ["name" => "Islândia", "name_no_accents" => "Islandia"],
    ["name" => "Itália", "name_no_accents" => "Italia"],
    ["name" => "Jamaica", "name_no_accents" => "Jamaica"],
    ["name" => "Jordânia", "name_no_accents" => "Jordania"],
    ["name" => "Japão", "name_no_accents" => "Japao"],
    ["name" => "Quênia", "name_no_accents" => "Quenia"],
    ["name" => "Quirguistão", "name_no_accents" => "Quirguistao"],
    ["name" => "Camboja", "name_no_accents" => "Camboja"],
    ["name" => "Kiribati", "name_no_accents" => "Kiribati"],
    ["name" => "Comores", "name_no_accents" => "Comores"],
    ["name" => "Coreia do Norte", "name_no_accents" => "Coreia do Norte"],
    ["name" => "Coreia do Sul", "name_no_accents" => "Coreia do Sul"],
    ["name" => "Kuwait", "name_no_accents" => "Kuwait"],
    ["name" => "Cazaquistão", "name_no_accents" => "Cazaquistao"],
    ["name" => "Laos", "name_no_accents" => "Laos"],
    ["name" => "Líbano", "name_no_accents" => "Libano"],
    ["name" => "Santa Lúcia", "name_no_accents" => "Santa Lucia"],
    ["name" => "Liechtenstein", "name_no_accents" => "Liechtenstein"],
    ["name" => "Sri Lanka", "name_no_accents" => "Sri Lanka"],
    ["name" => "Libéria", "name_no_accents" => "Liberia"],
    ["name" => "Lesoto", "name_no_accents" => "Lesoto"],
    ["name" => "Lituânia", "name_no_accents" => "Lituania"],
    ["name" => "Luxemburgo", "name_no_accents" => "Luxemburgo"],
    ["name" => "Letônia", "name_no_accents" => "Letonia"],
    ["name" => "Líbia", "name_no_accents" => "Libia"],
    ["name" => "Marrocos", "name_no_accents" => "Marrocos"],
    ["name" => "Mónaco", "name_no_accents" => "Monaco"],
    ["name" => "Moldávia", "name_no_accents" => "Moldavia"],
    ["name" => "Montenegro", "name_no_accents" => "Montenegro"],
    ["name" => "Madagáscar", "name_no_accents" => "Madagascar"],
    ["name" => "Macedónia do Norte", "name_no_accents" => "Macedonia do Norte"],
    ["name" => "Mali", "name_no_accents" => "Mali"],
    ["name" => "Mongólia", "name_no_accents" => "Mongolia"],
    ["name" => "Macau", "name_no_accents" => "Macau"],
    ["name" => "Martinica", "name_no_accents" => "Martinica"],
    ["name" => "Mauritânia", "name_no_accents" => "Mauritania"],
    ["name" => "Malta", "name_no_accents" => "Malta"],
    ["name" => "Maurícia", "name_no_accents" => "Mauricia"],
    ["name" => "Maldivas", "name_no_accents" => "Maldivas"],
    ["name" => "Malawi", "name_no_accents" => "Malawi"],
    ["name" => "México", "name_no_accents" => "Mexico"],
    ["name" => "Malásia", "name_no_accents" => "Malasia"],
    ["name" => "Moçambique", "name_no_accents" => "Mocambique"],
    ["name" => "Namíbia", "name_no_accents" => "Namibia"],
    ["name" => "Níger", "name_no_accents" => "Niger"],
    ["name" => "Nigéria", "name_no_accents" => "Nigeria"],
    ["name" => "Nicarágua", "name_no_accents" => "Nicaragua"],
    ["name" => "Países Baixos", "name_no_accents" => "Paises Baixos"],
    ["name" => "Noruega", "name_no_accents" => "Noruega"],
    ["name" => "Nepal", "name_no_accents" => "Nepal"],
    ["name" => "Nova Zelândia", "name_no_accents" => "Nova Zelandia"],
    ["name" => "Panamá", "name_no_accents" => "Panama"],
    ["name" => "Peru", "name_no_accents" => "Peru"],
    ["name" => "Papua-Nova Guiné", "name_no_accents" => "Papua-Nova Guine"],
    ["name" => "Filipinas", "name_no_accents" => "Filipinas"],
    ["name" => "Paquistão", "name_no_accents" => "Paquistao"],
    ["name" => "Polônia", "name_no_accents" => "Polonia"],
    ["name" => "Porto Rico", "name_no_accents" => "Porto Rico"],
    ["name" => "Palestina", "name_no_accents" => "Palestina"],
    ["name" => "Portugal", "name_no_accents" => "Portugal"],
    ["name" => "Paraguai", "name_no_accents" => "Paraguai"],
    ["name" => "Catar", "name_no_accents" => "Catar"],
    ["name" => "Romênia", "name_no_accents" => "Romenia"],
    ["name" => "Sérvia", "name_no_accents" => "Servia"],
    ["name" => "Rússia", "name_no_accents" => "Russia"],
    ["name" => "Ruanda", "name_no_accents" => "Ruanda"],
    ["name" => "Arábia Saudita", "name_no_accents" => "Arabia Saudita"],
    ["name" => "Sudão", "name_no_accents" => "Sudao"],
    ["name" => "Suécia", "name_no_accents" => "Suecia"],
    ["name" => "Singapura", "name_no_accents" => "Singapura"],
    ["name" => "Eslovênia", "name_no_accents" => "Eslovenia"],
    ["name" => "Eslováquia", "name_no_accents" => "Eslovaquia"],
    ["name" => "Serra Leoa", "name_no_accents" => "Serra Leoa"],
    ["name" => "Senegal", "name_no_accents" => "Senegal"],
    ["name" => "Somália", "name_no_accents" => "Somalia"],
    ["name" => "Suriname", "name_no_accents" => "Suriname"],
    ["name" => "Sudão do Sul", "name_no_accents" => "Sudao do Sul"],
    ["name" => "São Tomé e Príncipe", "name_no_accents" => "Sao Tome e Principe"],
    ["name" => "El Salvador", "name_no_accents" => "El Salvador"],
    ["name" => "Síria", "name_no_accents" => "Siria"],
    ["name" => "Essuatíni", "name_no_accents" => "Essuatini"],
    ["name" => "Chade", "name_no_accents" => "Chade"],
    ["name" => "Togo", "name_no_accents" => "Togo"],
    ["name" => "Tailândia", "name_no_accents" => "Tailandia"],
    ["name" => "Tajiquistão", "name_no_accents" => "Tajiquistao"],
    ["name" => "Timor-Leste", "name_no_accents" => "Timor-Leste"],
    ["name" => "Turcomenistão", "name_no_accents" => "Turcomenistao"],
    ["name" => "Tunísia", "name_no_accents" => "Tunisia"],
    ["name" => "Turquia", "name_no_accents" => "Turquia"],
    ["name" => "Tuvalu", "name_no_accents" => "Tuvalu"],
    ["name" => "Taiwan", "name_no_accents" => "Taiwan"],
    ["name" => "Tanzânia", "name_no_accents" => "Tanzania"],
    ["name" => "Ucrânia", "name_no_accents" => "Ucrania"],
    ["name" => "Uganda", "name_no_accents" => "Uganda"],
    ["name" => "Estados Unidos", "name_no_accents" => "Estados Unidos"],
    ["name" => "Uruguai", "name_no_accents" => "Uruguai"],
    ["name" => "Uzbequistão", "name_no_accents" => "Uzbequistao"],
    ["name" => "Vaticano", "name_no_accents" => "Vaticano"],
    ["name" => "Venezuela", "name_no_accents" => "Venezuela"],
    ["name" => "Vietnã", "name_no_accents" => "Vietna"],
    ["name" => "Kosovo", "name_no_accents" => "Kosovo"],
    ["name" => "Iémen", "name_no_accents" => "Iemen"],
    ["name" => "África do Sul", "name_no_accents" => "Africa do Sul"],
    ["name" => "Zâmbia", "name_no_accents" => "Zambia"],
    ["name" => "Zimbabwe", "name_no_accents" => "Zimbabwe"]
];

echo json_encode($countries);
?>