<?php
$countries = [
    ["name" => "Andorra", "flag" => "ad" ],
    ["name" => "Emirados Árabes Unidos", "flag" => "ae" ],
    ["name" => "Afeganistão", "flag" => "af" ],
    ["name" => "Anguila", "flag" => "ai" ],
    ["name" => "Albânia", "flag" => "al" ],
    ["name" => "Arménia", "flag" => "am" ],
    ["name" => "Angola", "flag" => "ao" ],
    ["name" => "Antártida", "flag" => "aq" ],
    ["name" => "Argentina", "flag" => "ar" ],
    ["name" => "Áustria", "flag" => "at" ],
    ["name" => "Austrália", "flag" => "au" ],
    ["name" => "Azerbaijão", "flag" => "az" ],
    ["name" => "Bósnia e Herzegovina", "flag" => "ba" ],
    ["name" => "Barbados", "flag" => "bb" ],
    ["name" => "Bangladesh", "flag" => "bd" ],
    ["name" => "Bélgica", "flag" => "be" ],
    ["name" => "Burquina Fasso", "flag" => "bf" ],
    ["name" => "Bulgária", "flag" => "bg" ],
    ["name" => "Bahrein", "flag" => "bh" ],
    ["name" => "Burundi", "flag" => "bi" ],
    ["name" => "Benim", "flag" => "bj" ],
    ["name" => "Bermudas", "flag" => "bm" ],
    ["name" => "Brunei", "flag" => "bn" ],
    ["name" => "Bolívia", "flag" => "bo" ],
    ["name" => "Brasil", "flag" => "br" ],
    ["name" => "Bahamas", "flag" => "bs" ],
    ["name" => "Butão", "flag" => "bt" ],
    ["name" => "Botswana", "flag" => "bw" ],
    ["name" => "Bielorrússia", "flag" => "by" ],
    ["name" => "Belize", "flag" => "bz" ],
    ["name" => "Canadá", "flag" => "ca" ],
    ["name" => "República Democrática do Congo", "flag" => "cd" ],
    ["name" => "República Centro-Africana", "flag" => "cf" ],
    ["name" => "República do Congo", "flag" => "cg" ],
    ["name" => "Suíça", "flag" => "ch" ],
    ["name" => "Costa do Marfim", "flag" => "ci" ],
    ["name" => "Chile", "flag" => "cl" ],
    ["name" => "Camarões", "flag" => "cm" ],
    ["name" => "China", "flag" => "cn" ],
    ["name" => "Colômbia", "flag" => "co" ],
    ["name" => "Costa Rica", "flag" => "cr" ],
    ["name" => "Cuba", "flag" => "cu" ],
    ["name" => "Cabo Verde", "flag" => "cv" ],
    ["name" => "Chipre", "flag" => "cy" ],
    ["name" => "República Tcheca", "flag" => "cz" ],
    ["name" => "Alemanha", "flag" => "de" ],
    ["name" => "Djibouti", "flag" => "dj" ],
    ["name" => "Dinamarca", "flag" => "dk" ],
    ["name" => "Dominica", "flag" => "dm" ],
    ["name" => "República Dominicana", "flag" => "do" ],
    ["name" => "Argélia", "flag" => "dz" ],
    ["name" => "Equador", "flag" => "ec" ],
    ["name" => "Estônia", "flag" => "ee" ],
    ["name" => "Egito", "flag" => "eg" ],
    ["name" => "Eritreia", "flag" => "er" ],
    ["name" => "Espanha", "flag" => "es" ],
    ["name" => "Etiópia", "flag" => "et" ],
    ["name" => "Finlândia", "flag" => "fi" ],
    ["name" => "França", "flag" => "fr" ],
    ["name" => "Gabão", "flag" => "ga" ],
    ["name" => "Reino Unido", "flag" => "gb" ],
    ["name" => "Inglaterra", "flag" => "gb-eng" ],
    ["name" => "Irlanda do Norte", "flag" => "gb-nir" ],
    ["name" => "Escócia", "flag" => "gb-sct" ],
    ["name" => "País de Gales", "flag" => "gb-wls" ],
    ["name" => "Granada", "flag" => "gd" ],
    ["name" => "Geórgia", "flag" => "ge" ],
    ["name" => "Guiana Francesa", "flag" => "gf" ],
    ["name" => "Gana", "flag" => "gh" ],
    ["name" => "Gibraltar", "flag" => "gi" ],
    ["name" => "Groelândia", "flag" => "gl" ],
    ["name" => "Gâmbia", "flag" => "gm" ],
    ["name" => "Guiné", "flag" => "gn" ],
    ["name" => "Guadalupe", "flag" => "gp" ],
    ["name" => "Guiné Equatorial", "flag" => "gq" ],
    ["name" => "Grécia", "flag" => "gr" ],
    ["name" => "Guatemala", "flag" => "gt" ],
    ["name" => "Guiné-Bissau", "flag" => "gw" ],
    ["name" => "Guiana", "flag" => "gy" ],
    ["name" => "Hong Kong", "flag" => "hk" ],
    ["name" => "Honduras", "flag" => "hn" ],
    ["name" => "Croácia", "flag" => "hr" ],
    ["name" => "Haiti", "flag" => "ht" ],
    ["name" => "Hungria", "flag" => "hu" ],
    ["name" => "Indonésia", "flag" => "id" ],
    ["name" => "Irlanda", "flag" => "ie" ],
    ["name" => "Israel", "flag" => "il" ],
    ["name" => "Índia", "flag" => "in" ],
    ["name" => "Iraque", "flag" => "iq" ],
    ["name" => "Irã", "flag" => "ir" ],
    ["name" => "Islândia", "flag" => "is" ],
    ["name" => "Itália", "flag" => "it" ],
    ["name" => "Jamaica", "flag" => "jm" ],
    ["name" => "Jordânia", "flag" => "jo" ],
    ["name" => "Japão", "flag" => "jp" ],
    ["name" => "Quênia", "flag" => "ke" ],
    ["name" => "Quirguistão", "flag" => "kg" ],
    ["name" => "Camboja", "flag" => "kh" ],
    ["name" => "Comores", "flag" => "km" ],
    ["name" => "Coreia do Norte", "flag" => "kp" ],
    ["name" => "Coreia do Sul", "flag" => "kr" ],
    ["name" => "Kuwait", "flag" => "kw" ],
    ["name" => "Ilhas Cayman", "flag" => "ky" ],
    ["name" => "Cazaquistão", "flag" => "kz" ],
    ["name" => "Laos", "flag" => "la" ],
    ["name" => "Líbano", "flag" => "lb" ],
    ["name" => "Santa Lúcia", "flag" => "lc" ],
    ["name" => "Liechtenstein", "flag" => "li" ],
    ["name" => "Sri Lanka", "flag" => "lk" ],
    ["name" => "Libéria", "flag" => "lr" ],
    ["name" => "Lesoto", "flag" => "ls" ],
    ["name" => "Lituânia", "flag" => "lt" ],
    ["name" => "Luxemburgo", "flag" => "lu" ],
    ["name" => "Letônia", "flag" => "lv" ],
    ["name" => "Líbia", "flag" => "ly" ],
    ["name" => "Marrocos", "flag" => "ma" ],
    ["name" => "Mónaco", "flag" => "mc" ],
    ["name" => "Moldávia", "flag" => "md" ],
    ["name" => "Montenegro", "flag" => "me" ],
    ["name" => "Madagáscar", "flag" => "mg" ],
    ["name" => "Macedónia do Norte", "flag" => "mk" ],
    ["name" => "Mali", "flag" => "ml" ],
    ["name" => "Mongólia", "flag" => "mn" ],
    ["name" => "Macau", "flag" => "mo" ],
    ["name" => "Martinica", "flag" => "mq" ],
    ["name" => "Mauritânia", "flag" => "mr" ],
    ["name" => "Malta", "flag" => "mt" ],
    ["name" => "Maurícia", "flag" => "mu" ],
    ["name" => "Maldivas", "flag" => "mv" ],
    ["name" => "Malawi", "flag" => "mw" ],
    ["name" => "México", "flag" => "mx" ],
    ["name" => "Malásia", "flag" => "my" ],
    ["name" => "Moçambique", "flag" => "mz" ],
    ["name" => "Namíbia", "flag" => "na" ],
    ["name" => "Níger", "flag" => "ne" ],
    ["name" => "Nigéria", "flag" => "ng" ],
    ["name" => "Nicarágua", "flag" => "ni" ],
    ["name" => "Países Baixos", "flag" => "nl" ],
    ["name" => "Noruega", "flag" => "no" ],
    ["name" => "Nepal", "flag" => "np" ],
    ["name" => "Nova Zelândia", "flag" => "nz" ],
    ["name" => "Panamá", "flag" => "pa" ],
    ["name" => "Peru", "flag" => "pe" ],
    ["name" => "Papua-Nova Guiné", "flag" => "pg" ],
    ["name" => "Filipinas", "flag" => "ph" ],
    ["name" => "Paquistão", "flag" => "pk" ],
    ["name" => "Polônia", "flag" => "pl" ],
    ["name" => "Porto Rico", "flag" => "pr" ],
    ["name" => "Palestina", "flag" => "ps" ],
    ["name" => "Portugal", "flag" => "pt" ],
    ["name" => "Paraguai", "flag" => "py" ],
    ["name" => "Catar", "flag" => "qa" ],
    ["name" => "Romênia", "flag" => "ro" ],
    ["name" => "Sérvia", "flag" => "rs" ],
    ["name" => "Rússia", "flag" => "ru" ],
    ["name" => "Ruanda", "flag" => "rw" ],
    ["name" => "Arábia Saudita", "flag" => "sa" ],
    ["name" => "Sudão", "flag" => "sd" ],
    ["name" => "Suécia", "flag" => "se" ],
    ["name" => "Singapura", "flag" => "sg" ],
    ["name" => "Eslovênia", "flag" => "si" ],
    ["name" => "Eslováquia", "flag" => "sk" ],
    ["name" => "Serra Leoa", "flag" => "sl" ],
    ["name" => "Senegal", "flag" => "sn" ],
    ["name" => "Somália", "flag" => "so" ],
    ["name" => "Suriname", "flag" => "sr" ],
    ["name" => "Sudão do Sul", "flag" => "ss" ],
    ["name" => "São Tomé e Príncipe", "flag" => "st" ],
    ["name" => "El Salvador", "flag" => "sv" ],
    ["name" => "Síria", "flag" => "sy" ],
    ["name" => "Essuatíni", "flag" => "sz" ],
    ["name" => "Chade", "flag" => "td" ],
    ["name" => "Togo", "flag" => "tg" ],
    ["name" => "Tailândia", "flag" => "th" ],
    ["name" => "Tajiquistão", "flag" => "tj" ],
    ["name" => "Timor-Leste", "flag" => "tl" ],
    ["name" => "Turcomenistão", "flag" => "tm" ],
    ["name" => "Tunísia", "flag" => "tn" ],
    ["name" => "Turquia", "flag" => "tr" ],
    ["name" => "Tuvalu", "flag" => "tv" ],
    ["name" => "Taiwan", "flag" => "tw" ],
    ["name" => "Tanzânia", "flag" => "tz" ],
    ["name" => "Ucrânia", "flag" => "ua" ],
    ["name" => "Uganda", "flag" => "ug" ],
    ["name" => "Estados Unidos", "flag" => "us" ],
    ["name" => "Uruguai", "flag" => "uy" ],
    ["name" => "Uzbequistão", "flag" => "uz" ],
    ["name" => "Vaticano", "flag" => "va" ],
    ["name" => "Venezuela", "flag" => "ve" ],
    ["name" => "Vietnã", "flag" => "vn" ],
    ["name" => "Kosovo", "flag" => "xk" ],
    ["name" => "Iémen", "flag" => "ye" ],
    ["name" => "África do Sul", "flag" => "za" ],
    ["name" => "Zâmbia", "flag" => "zm" ],
    ["name" => "Zimbabwe", "flag" => "zw"]    
];

$randomIndex = array_rand($countries);
$randomCountry = $countries[$randomIndex];

// Montar um array com os dados que você deseja enviar
$responseData = [
    "name" => $randomCountry['name'],
    "flag" => $randomCountry['flag'],
    "country_image" => "flags/" . $randomCountry["flag"] . ".png"
];

// Retornar o array como JSON
echo json_encode($responseData);
?>
